### PR TITLE
Prototyped mine collecting. Currently, when the players collide with …

### PR DESCRIPTION
**Pull request by HarryRabinowitz**
…the mine pickup, the mine destroys itself at sets a bool in the player script to true. When you place a mine, it gets sets to false once more.

2 Problems:
a. Any player, including the ball, can pick up mines.
b. When one runner picks up a mine, both runners are set to "true" and can both place mines.

### CODE REVIEW

**Comment by jirrian** [comment]
I think you have to merge your branch with master first.
Also you can resolve the issues by using tags that I wrote in my pull request (I also added it to the doc). Just check other.tag inside OnTriggerEnter.

**Comment by jirrian** [comment]
Also make sure when you merge, you overwrite the runnerOneControls/runnerTwoControls currently in master with yours.
The ones I added to master were just placeholders.

**Comment by HarryRabinowitz** [comment]
Pretty sure I have merged. Let's deal with this in class, to be safe.

**Comment by ailise** [comment]
Got it, will not merge yet. Thanks Harry!

**Pull request closed without merging**
